// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/ijalalfrz/coupon-system/internal/app/model"
	"github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCouponRepositoryRedeemer creates a new instance of MockCouponRepositoryRedeemer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCouponRepositoryRedeemer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCouponRepositoryRedeemer {
	mock := &MockCouponRepositoryRedeemer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCouponRepositoryRedeemer is an autogenerated mock type for the CouponRepositoryRedeemer type
type MockCouponRepositoryRedeemer struct {
	mock.Mock
}

type MockCouponRepositoryRedeemer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCouponRepositoryRedeemer) EXPECT() *MockCouponRepositoryRedeemer_Expecter {
	return &MockCouponRepositoryRedeemer_Expecter{mock: &_m.Mock}
}

// GetCouponForUpdateTx provides a mock function for the type MockCouponRepositoryRedeemer
func (_mock *MockCouponRepositoryRedeemer) GetCouponForUpdateTx(ctx context.Context, tx *sqlx.Tx, couponName string) (model.Coupon, error) {
	ret := _mock.Called(ctx, tx, couponName)

	if len(ret) == 0 {
		panic("no return value specified for GetCouponForUpdateTx")
	}

	var r0 model.Coupon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) (model.Coupon, error)); ok {
		return returnFunc(ctx, tx, couponName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) model.Coupon); ok {
		r0 = returnFunc(ctx, tx, couponName)
	} else {
		r0 = ret.Get(0).(model.Coupon)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = returnFunc(ctx, tx, couponName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCouponForUpdateTx'
type MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call struct {
	*mock.Call
}

// GetCouponForUpdateTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - couponName string
func (_e *MockCouponRepositoryRedeemer_Expecter) GetCouponForUpdateTx(ctx interface{}, tx interface{}, couponName interface{}) *MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call {
	return &MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call{Call: _e.mock.On("GetCouponForUpdateTx", ctx, tx, couponName)}
}

func (_c *MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, couponName string)) *MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call) Return(coupon model.Coupon, err error) *MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call {
	_c.Call.Return(coupon, err)
	return _c
}

func (_c *MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call) RunAndReturn(run func(ctx context.Context, tx *sqlx.Tx, couponName string) (model.Coupon, error)) *MockCouponRepositoryRedeemer_GetCouponForUpdateTx_Call {
	_c.Call.Return(run)
	return _c
}

// SubstractRemainingAmountTx provides a mock function for the type MockCouponRepositoryRedeemer
func (_mock *MockCouponRepositoryRedeemer) SubstractRemainingAmountTx(ctx context.Context, tx *sqlx.Tx, couponName string, amount int) error {
	ret := _mock.Called(ctx, tx, couponName, amount)

	if len(ret) == 0 {
		panic("no return value specified for SubstractRemainingAmountTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, int) error); ok {
		r0 = returnFunc(ctx, tx, couponName, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubstractRemainingAmountTx'
type MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call struct {
	*mock.Call
}

// SubstractRemainingAmountTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - couponName string
//   - amount int
func (_e *MockCouponRepositoryRedeemer_Expecter) SubstractRemainingAmountTx(ctx interface{}, tx interface{}, couponName interface{}, amount interface{}) *MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call {
	return &MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call{Call: _e.mock.On("SubstractRemainingAmountTx", ctx, tx, couponName, amount)}
}

func (_c *MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, couponName string, amount int)) *MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call) Return(err error) *MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call) RunAndReturn(run func(ctx context.Context, tx *sqlx.Tx, couponName string, amount int) error) *MockCouponRepositoryRedeemer_SubstractRemainingAmountTx_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockCouponRepositoryRedeemer
func (_mock *MockCouponRepositoryRedeemer) WithTransaction(ctx context.Context, txFunc func(context.Context, *sqlx.Tx) error) error {
	ret := _mock.Called(ctx, txFunc)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context, *sqlx.Tx) error) error); ok {
		r0 = returnFunc(ctx, txFunc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCouponRepositoryRedeemer_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockCouponRepositoryRedeemer_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - txFunc func(context.Context, *sqlx.Tx) error
func (_e *MockCouponRepositoryRedeemer_Expecter) WithTransaction(ctx interface{}, txFunc interface{}) *MockCouponRepositoryRedeemer_WithTransaction_Call {
	return &MockCouponRepositoryRedeemer_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, txFunc)}
}

func (_c *MockCouponRepositoryRedeemer_WithTransaction_Call) Run(run func(ctx context.Context, txFunc func(context.Context, *sqlx.Tx) error)) *MockCouponRepositoryRedeemer_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context, *sqlx.Tx) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context, *sqlx.Tx) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCouponRepositoryRedeemer_WithTransaction_Call) Return(err error) *MockCouponRepositoryRedeemer_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCouponRepositoryRedeemer_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, txFunc func(context.Context, *sqlx.Tx) error) error) *MockCouponRepositoryRedeemer_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCouponClaimRepositoryWriter creates a new instance of MockCouponClaimRepositoryWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCouponClaimRepositoryWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCouponClaimRepositoryWriter {
	mock := &MockCouponClaimRepositoryWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCouponClaimRepositoryWriter is an autogenerated mock type for the CouponClaimRepositoryWriter type
type MockCouponClaimRepositoryWriter struct {
	mock.Mock
}

type MockCouponClaimRepositoryWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCouponClaimRepositoryWriter) EXPECT() *MockCouponClaimRepositoryWriter_Expecter {
	return &MockCouponClaimRepositoryWriter_Expecter{mock: &_m.Mock}
}

// CreateCouponClaimTx provides a mock function for the type MockCouponClaimRepositoryWriter
func (_mock *MockCouponClaimRepositoryWriter) CreateCouponClaimTx(ctx context.Context, tx *sqlx.Tx, couponClaim model.CouponClaim) error {
	ret := _mock.Called(ctx, tx, couponClaim)

	if len(ret) == 0 {
		panic("no return value specified for CreateCouponClaimTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, model.CouponClaim) error); ok {
		r0 = returnFunc(ctx, tx, couponClaim)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCouponClaimTx'
type MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call struct {
	*mock.Call
}

// CreateCouponClaimTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - couponClaim model.CouponClaim
func (_e *MockCouponClaimRepositoryWriter_Expecter) CreateCouponClaimTx(ctx interface{}, tx interface{}, couponClaim interface{}) *MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call {
	return &MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call{Call: _e.mock.On("CreateCouponClaimTx", ctx, tx, couponClaim)}
}

func (_c *MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, couponClaim model.CouponClaim)) *MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		var arg2 model.CouponClaim
		if args[2] != nil {
			arg2 = args[2].(model.CouponClaim)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call) Return(err error) *MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call) RunAndReturn(run func(ctx context.Context, tx *sqlx.Tx, couponClaim model.CouponClaim) error) *MockCouponClaimRepositoryWriter_CreateCouponClaimTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCouponRepositoryWriter creates a new instance of MockCouponRepositoryWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCouponRepositoryWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCouponRepositoryWriter {
	mock := &MockCouponRepositoryWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCouponRepositoryWriter is an autogenerated mock type for the CouponRepositoryWriter type
type MockCouponRepositoryWriter struct {
	mock.Mock
}

type MockCouponRepositoryWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCouponRepositoryWriter) EXPECT() *MockCouponRepositoryWriter_Expecter {
	return &MockCouponRepositoryWriter_Expecter{mock: &_m.Mock}
}

// CreateTx provides a mock function for the type MockCouponRepositoryWriter
func (_mock *MockCouponRepositoryWriter) CreateTx(ctx context.Context, tx *sqlx.Tx, coupon model.Coupon) error {
	ret := _mock.Called(ctx, tx, coupon)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, model.Coupon) error); ok {
		r0 = returnFunc(ctx, tx, coupon)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCouponRepositoryWriter_CreateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTx'
type MockCouponRepositoryWriter_CreateTx_Call struct {
	*mock.Call
}

// CreateTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - coupon model.Coupon
func (_e *MockCouponRepositoryWriter_Expecter) CreateTx(ctx interface{}, tx interface{}, coupon interface{}) *MockCouponRepositoryWriter_CreateTx_Call {
	return &MockCouponRepositoryWriter_CreateTx_Call{Call: _e.mock.On("CreateTx", ctx, tx, coupon)}
}

func (_c *MockCouponRepositoryWriter_CreateTx_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, coupon model.Coupon)) *MockCouponRepositoryWriter_CreateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		var arg2 model.Coupon
		if args[2] != nil {
			arg2 = args[2].(model.Coupon)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCouponRepositoryWriter_CreateTx_Call) Return(err error) *MockCouponRepositoryWriter_CreateTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCouponRepositoryWriter_CreateTx_Call) RunAndReturn(run func(ctx context.Context, tx *sqlx.Tx, coupon model.Coupon) error) *MockCouponRepositoryWriter_CreateTx_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockCouponRepositoryWriter
func (_mock *MockCouponRepositoryWriter) WithTransaction(ctx context.Context, txFunc func(context.Context, *sqlx.Tx) error) error {
	ret := _mock.Called(ctx, txFunc)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context, *sqlx.Tx) error) error); ok {
		r0 = returnFunc(ctx, txFunc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCouponRepositoryWriter_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockCouponRepositoryWriter_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - txFunc func(context.Context, *sqlx.Tx) error
func (_e *MockCouponRepositoryWriter_Expecter) WithTransaction(ctx interface{}, txFunc interface{}) *MockCouponRepositoryWriter_WithTransaction_Call {
	return &MockCouponRepositoryWriter_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, txFunc)}
}

func (_c *MockCouponRepositoryWriter_WithTransaction_Call) Run(run func(ctx context.Context, txFunc func(context.Context, *sqlx.Tx) error)) *MockCouponRepositoryWriter_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context, *sqlx.Tx) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context, *sqlx.Tx) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCouponRepositoryWriter_WithTransaction_Call) Return(err error) *MockCouponRepositoryWriter_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCouponRepositoryWriter_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, txFunc func(context.Context, *sqlx.Tx) error) error) *MockCouponRepositoryWriter_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCouponRepositoryReader creates a new instance of MockCouponRepositoryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCouponRepositoryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCouponRepositoryReader {
	mock := &MockCouponRepositoryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCouponRepositoryReader is an autogenerated mock type for the CouponRepositoryReader type
type MockCouponRepositoryReader struct {
	mock.Mock
}

type MockCouponRepositoryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCouponRepositoryReader) EXPECT() *MockCouponRepositoryReader_Expecter {
	return &MockCouponRepositoryReader_Expecter{mock: &_m.Mock}
}

// GetCouponByName provides a mock function for the type MockCouponRepositoryReader
func (_mock *MockCouponRepositoryReader) GetCouponByName(ctx context.Context, couponName string) (model.Coupon, error) {
	ret := _mock.Called(ctx, couponName)

	if len(ret) == 0 {
		panic("no return value specified for GetCouponByName")
	}

	var r0 model.Coupon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Coupon, error)); ok {
		return returnFunc(ctx, couponName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Coupon); ok {
		r0 = returnFunc(ctx, couponName)
	} else {
		r0 = ret.Get(0).(model.Coupon)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, couponName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCouponRepositoryReader_GetCouponByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCouponByName'
type MockCouponRepositoryReader_GetCouponByName_Call struct {
	*mock.Call
}

// GetCouponByName is a helper method to define mock.On call
//   - ctx context.Context
//   - couponName string
func (_e *MockCouponRepositoryReader_Expecter) GetCouponByName(ctx interface{}, couponName interface{}) *MockCouponRepositoryReader_GetCouponByName_Call {
	return &MockCouponRepositoryReader_GetCouponByName_Call{Call: _e.mock.On("GetCouponByName", ctx, couponName)}
}

func (_c *MockCouponRepositoryReader_GetCouponByName_Call) Run(run func(ctx context.Context, couponName string)) *MockCouponRepositoryReader_GetCouponByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCouponRepositoryReader_GetCouponByName_Call) Return(coupon model.Coupon, err error) *MockCouponRepositoryReader_GetCouponByName_Call {
	_c.Call.Return(coupon, err)
	return _c
}

func (_c *MockCouponRepositoryReader_GetCouponByName_Call) RunAndReturn(run func(ctx context.Context, couponName string) (model.Coupon, error)) *MockCouponRepositoryReader_GetCouponByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCouponClaimRepositoryReader creates a new instance of MockCouponClaimRepositoryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCouponClaimRepositoryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCouponClaimRepositoryReader {
	mock := &MockCouponClaimRepositoryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCouponClaimRepositoryReader is an autogenerated mock type for the CouponClaimRepositoryReader type
type MockCouponClaimRepositoryReader struct {
	mock.Mock
}

type MockCouponClaimRepositoryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCouponClaimRepositoryReader) EXPECT() *MockCouponClaimRepositoryReader_Expecter {
	return &MockCouponClaimRepositoryReader_Expecter{mock: &_m.Mock}
}

// GetAllCouponClaimByCouponName provides a mock function for the type MockCouponClaimRepositoryReader
func (_mock *MockCouponClaimRepositoryReader) GetAllCouponClaimByCouponName(ctx context.Context, couponName string) ([]string, error) {
	ret := _mock.Called(ctx, couponName)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCouponClaimByCouponName")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, couponName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, couponName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, couponName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCouponClaimByCouponName'
type MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call struct {
	*mock.Call
}

// GetAllCouponClaimByCouponName is a helper method to define mock.On call
//   - ctx context.Context
//   - couponName string
func (_e *MockCouponClaimRepositoryReader_Expecter) GetAllCouponClaimByCouponName(ctx interface{}, couponName interface{}) *MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call {
	return &MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call{Call: _e.mock.On("GetAllCouponClaimByCouponName", ctx, couponName)}
}

func (_c *MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call) Run(run func(ctx context.Context, couponName string)) *MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call) Return(strings []string, err error) *MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call) RunAndReturn(run func(ctx context.Context, couponName string) ([]string, error)) *MockCouponClaimRepositoryReader_GetAllCouponClaimByCouponName_Call {
	_c.Call.Return(run)
	return _c
}
